
import java.awt.Color;
import java.awt.Graphics;
import javax.swing.DefaultListModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author Amine
 */
public class Classement extends javax.swing.JDialog {
    private LesJoueurs lesJo;
    private LesParties lesPa;
    private int tabC[];
    
    /**
     * Creates new form Classement
     */
    public Classement(java.awt.Frame parent, boolean modal,LesJoueurs lesj,LesParties lp) {
        super(parent, modal);
        initComponents();
        this.lesJo=lesj;
        this.lesPa=lp;
        Edition.setText(this.lesJo.toString());
        this.tabC = new int[this.lesJo.getNbJoueurs()];
        initClassement();
        initListeJoueursClasses();
    }
    
    private void initClassement(){
        int max = 0;
        for(int i=0;i<tabC.length;i++){
            tabC[i]=i;
        }    
        for(int i=0;i<tabC.length-1;i++){
            max = this.lesJo.getJoueur(tabC[i]).getNbpartiesGagnees();
            for(int j=i+1; j<this.tabC.length; j++){
                if(this.lesJo.getJoueur(tabC[j]).getNbpartiesGagnees()>max){
                    int temp = tabC[i];
                    tabC[i]=tabC[j];
                    tabC[j]=temp;
                }
            }
        }
    }
    @Override
    public void paint(Graphics g){
        super.paint(g);
        dessineHisto();
    }
    
    private void initListeJoueursClasses(){
        DefaultListModel mod = new DefaultListModel();
        this.ListeClassement.setModel(mod);
        for (int i=0;i<this.lesJo.getNbJoueurs();i++){
            mod.addElement(""+(i+1)+this.lesJo.getJoueur(tabC[i]).getPseudo());
        }
    }
    
    private void dessineHisto(){
        Graphics g = PanHisto.getGraphics();
        int nbJo = this.lesJo.getNbJoueurs();
        int nbPa = this.lesPa.getNbPartie();
        int largeurMax = this.getWidth()/2;
        int decalageLarg = 50;
        int decalageHaut = 50;
        int largRect = largeurMax/nbJo;
        int hautMax = this.PanHisto.getHeight()/2;
        for(int i=0;i<nbJo;i++){
            Joueur j = this.lesJo.getJoueur(i);
            int nbPartG = j.getNbpartiesGagnees();
            int hautRectJ;
            if(nbPartG==0){
                hautRectJ=10;
            }else{
                hautRectJ = hautMax * nbPartG/nbPa;
            }
            int r = (int)(Math.random()*255);
            int v = (int)(Math.random()*255);
            int b = (int)(Math.random()*255);
            g.setColor(new Color(r,v,b));
            g.drawString(j.getPseudo(), i*largRect+decalageLarg, hautMax+decalageHaut+20);
            g.drawString(""+nbPartG, i*largRect+decalageLarg ,hautMax+decalageHaut+30);
            g.fillRect(i*largRect + decalageLarg, hautMax+decalageHaut-hautRectJ,largRect,hautRectJ);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jNorth = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jEast = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jEastScroll = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListeClassement = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        Edition = new javax.swing.JTextArea();
        PanHisto = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Statistiques joueurs");
        jNorth.add(jLabel1);

        getContentPane().add(jNorth, java.awt.BorderLayout.NORTH);

        jEast.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Classement des joueurs");
        jLabel2.setPreferredSize(new java.awt.Dimension(60, 26));
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jEast.add(jLabel2, java.awt.BorderLayout.NORTH);

        jEastScroll.setLayout(new java.awt.GridLayout(2, 1));

        ListeClassement.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ListeClassement);

        jEastScroll.add(jScrollPane1);

        Edition.setColumns(20);
        Edition.setRows(5);
        jScrollPane2.setViewportView(Edition);

        jEastScroll.add(jScrollPane2);

        jEast.add(jEastScroll, java.awt.BorderLayout.LINE_END);

        getContentPane().add(jEast, java.awt.BorderLayout.EAST);
        getContentPane().add(PanHisto, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Classement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Classement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Classement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Classement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Classement dialog = new Classement(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Edition;
    private javax.swing.JList<String> ListeClassement;
    private javax.swing.JPanel PanHisto;
    private javax.swing.JPanel jEast;
    private javax.swing.JPanel jEastScroll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jNorth;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
