import java.awt.*;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Amine
 */
public class PanneauImage extends javax.swing.JPanel {
    private Image img;
    /**
     * Creates new form PanneauImage
     */
    public PanneauImage() {
        super();
        this.img = null;
    }
    public PanneauImage(Image image){
        super();
        this.img = image;
    }
    public Image getImage(){
        return this.img;
    }
    public void setImage(Image image){
        this.img=image;
        this.repaint();
    }
    @Override
    public void paint(Graphics g){
        super.paint(g);
        if(img!=null){
            g.drawImage(img,0,0,this.getWidth(),this.getHeight(),this);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
