import java.awt.*;
import javax.swing.*;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author Amine
 */
public class SaisieJoueurDlg extends javax.swing.JDialog {
    private Joueur nj;//nouveau joueur
    private ImageIcon photo;
    private boolean ok;
    /**
     * Creates new form SaisieJoueurDlg
     */
    public SaisieJoueurDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.nj= new Joueur();
        BPhoto.setIcon(this.nj.getPhoto()); // BPhoto de type JButton
        this.ok=false;
        this.photo=this.nj.getPhoto();
    }
    //accesseurs get pour le joueur et pour ok
    public Joueur getJoueur(){
        return this.nj;
    }
    public boolean getOk(){
        return this.ok;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Pseudo = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        BParcourir = new javax.swing.JButton();
        BPhoto = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        BValider = new javax.swing.JButton();
        BAnnuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Saisie d'un nouveau joueur");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel5.setLayout(new java.awt.GridLayout(2, 2));

        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Pseudo ?");
        jPanel6.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel6);
        jPanel5.add(Pseudo);

        jPanel8.setLayout(new java.awt.GridLayout());

        jLabel3.setText("Photo ?");
        jPanel8.add(jLabel3);

        BParcourir.setText("Parcourir");
        BParcourir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BParcourirActionPerformed(evt);
            }
        });
        jPanel8.add(BParcourir);

        jPanel5.add(jPanel8);
        jPanel5.add(BPhoto);

        getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        BValider.setText("Valider");
        BValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BValiderActionPerformed(evt);
            }
        });
        jPanel4.add(BValider);

        BAnnuler.setText("Annuler");
        BAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAnnulerActionPerformed(evt);
            }
        });
        jPanel4.add(BAnnuler);

        getContentPane().add(jPanel4, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BValiderActionPerformed
        // TODO add your handling code here:
        this.nj.setPseudo(Pseudo.getText());
        this.nj.setPhoto(this.photo);
        this.ok=true;//fermeture par valider
        this.setVisible(false);//fermeture de la bôite
        this.dispose();//pour la gestion memoire
    }//GEN-LAST:event_BValiderActionPerformed

    private void BParcourirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BParcourirActionPerformed
        // TODO add your handling code here:
        JFileChooser jf= new JFileChooser();
        if (jf.showOpenDialog(this)== JFileChooser.APPROVE_OPTION){
            String path = jf.getSelectedFile().getPath();
            Image img=Toolkit.getDefaultToolkit().getImage(path);
            img=img.getScaledInstance(BPhoto.getWidth()-10, BPhoto.getHeight()-10, Image.SCALE_DEFAULT);
            this.photo = new ImageIcon(img); // attribute de la classe de type ImageIcon
            BPhoto.setIcon(photo); // BPhoto de type JButton
        } 
    }//GEN-LAST:event_BParcourirActionPerformed

    private void BAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAnnulerActionPerformed
        // TODO add your handling code here:
        this.ok=false;//fermeture par Annuler
        this.setVisible(false);//fermeture de la bôite
        this.dispose();//pour la gestion memoire
    }//GEN-LAST:event_BAnnulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaisieJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaisieJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaisieJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaisieJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SaisieJoueurDlg dialog = new SaisieJoueurDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAnnuler;
    private javax.swing.JButton BParcourir;
    private javax.swing.JButton BPhoto;
    private javax.swing.JButton BValider;
    private javax.swing.JTextField Pseudo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
