
import javax.swing.*;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author Amine
 */
public class SelectionJoueursDlg extends javax.swing.JDialog {
    
    private Joueur joueur1;
    private Joueur joueur2;
    private LesJoueurs lj;
    private boolean ok;
    /**
     * Creates new form SelectionJoueursDlg
     */
    public SelectionJoueursDlg(java.awt.Frame parent, boolean modal, LesJoueurs lj) {
        super(parent, modal);
        initComponents();
        this.joueur1=null;
        this.joueur2=null;
        this.lj=lj;
        initListesJoueurs();
        this.ok=false;
    }
    
    public Joueur getJoueur1(){
        return this.joueur1;
    }
    public Joueur getJoueur2(){
        return this.joueur2;
    }
    public boolean getOk(){
        return this.ok;
    }
    public void initListesJoueurs(){
        DefaultListModel mod=new DefaultListModel();
        LJoueursDispo.setModel(mod);
        for(int i = 0;i<this.lj.getNbJoueurs();i++){
            mod.addElement(this.lj.getJoueur(i).getPseudo());
        }
        DefaultListModel mod2=new DefaultListModel();
        LJoueurs.setModel(mod2);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PNorth = new javax.swing.JPanel();
        LTitre = new javax.swing.JLabel();
        PCenter = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LJoueursDispo = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        BAjouter = new javax.swing.JButton();
        BRetrait = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        LJoueurs = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        BValider = new javax.swing.JButton();
        BAnnuler = new javax.swing.JButton();
        LMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LTitre.setText("Sélection des deux joueurs");
        PNorth.add(LTitre);

        getContentPane().add(PNorth, java.awt.BorderLayout.NORTH);

        PCenter.setLayout(new java.awt.GridLayout(1, 3));

        LJoueursDispo.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(LJoueursDispo);

        PCenter.add(jScrollPane1);

        jPanel4.setLayout(new java.awt.GridLayout(4, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 133, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel1);

        BAjouter.setText("---->");
        BAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAjouterActionPerformed(evt);
            }
        });
        jPanel4.add(BAjouter);

        BRetrait.setText("<----");
        BRetrait.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRetraitActionPerformed(evt);
            }
        });
        jPanel4.add(BRetrait);

        PCenter.add(jPanel4);

        LJoueurs.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(LJoueurs);

        PCenter.add(jScrollPane2);

        getContentPane().add(PCenter, java.awt.BorderLayout.CENTER);

        BValider.setText("Valider");
        BValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BValiderActionPerformed(evt);
            }
        });
        jPanel3.add(BValider);

        BAnnuler.setText("Annuler");
        BAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAnnulerActionPerformed(evt);
            }
        });
        jPanel3.add(BAnnuler);
        jPanel3.add(LMessage);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BValiderActionPerformed
        // TODO add your handling code here:
        if(LJoueurs.getModel().getSize()==2){
            String ps1 = LJoueurs.getModel().getElementAt(0);
            String ps2 = LJoueurs.getModel().getElementAt(1);
            this.joueur1=this.lj.rechJoueur(ps1);
            this.joueur2=this.lj.rechJoueur(ps2);
            this.ok=true;
            this.setVisible(false);
            this.dispose();
        }
        else{
             LMessage.setText("Il faut 2 joueurs");
        }
        
    }//GEN-LAST:event_BValiderActionPerformed

    private void BAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAjouterActionPerformed
        // TODO add your handling code here:
        int ind = this.LJoueursDispo.getSelectedIndex();
        if(ind!=-1){// on vérifie qu'un élément est selectionné
         // on vérifie qu'il n'y a pas deja 2 joueur selectionnés
            if(this.LJoueurs.getModel().getSize()<2)
            {// recupération du pseudo sélectionné
                String ps= LJoueursDispo.getSelectedValue();
                DefaultListModel mod1= (DefaultListModel) LJoueursDispo.getModel();
                DefaultListModel mod2= (DefaultListModel) LJoueurs.getModel();
                mod1.remove(ind);
                mod2.addElement(ps);
            }
            
        }
    }//GEN-LAST:event_BAjouterActionPerformed

    private void BRetraitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRetraitActionPerformed
        // TODO add your handling code here:
        int ind = this.LJoueurs.getSelectedIndex();
        if(ind!=-1){
            String ps= this.LJoueurs.getSelectedValue();
            DefaultListModel mod1 = (DefaultListModel) this.LJoueursDispo.getModel();
            DefaultListModel mod2 = (DefaultListModel) this.LJoueursDispo.getModel();
            mod1.addElement(ps);
            mod2.remove(ind);
        }
    }//GEN-LAST:event_BRetraitActionPerformed

    private void BAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAnnulerActionPerformed
        // TODO add your handling code here:
        this.ok=false;//fermeture par Annuler
        this.setVisible(false);//fermeture de la bôite
        this.dispose();//pour la gestion memoire
    }//GEN-LAST:event_BAnnulerActionPerformed

    /**
     * @param args the command line arguments
     *//*
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SelectionJoueursDlg dialog = new SelectionJoueursDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAjouter;
    private javax.swing.JButton BAnnuler;
    private javax.swing.JButton BRetrait;
    private javax.swing.JButton BValider;
    private javax.swing.JList<String> LJoueurs;
    private javax.swing.JList<String> LJoueursDispo;
    private javax.swing.JLabel LMessage;
    private javax.swing.JLabel LTitre;
    private javax.swing.JPanel PCenter;
    private javax.swing.JPanel PNorth;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
