
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author Amine
 */
public class VisuJoueurDlg extends javax.swing.JDialog {
    private LesJoueurs lj;
    private Joueur jcourant;
    /**
     * Creates new form VisuJoueurDlg
     */
    public VisuJoueurDlg(java.awt.Frame parent, boolean modal, LesJoueurs llj) {
        super(parent, modal);
        initComponents();
        this.lj = new LesJoueurs();
        initListeNiveaux();
        this.jcourant=this.lj.getJoueur(0);
        afficheJoueurCourant();//pour afficher les informations du joueur
        this.setSize(600, 400);
        this.setLocationRelativeTo(null);// centrer l'interface
    }
    private void afficheJoueurCourant() { // Méthode affiche toute les information du joueur dans les zones destinées
        BRecherche.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                String pseudo = RechPseudo.getText();
                Joueur RP = lj.rechJoueur(pseudo);
                if (RP != null) {
                    Edition.setText("Joueur trouvé :\n" + RP.toString());
                    BPhoto.setIcon(RP.getPhoto());
                    Edition.setText(RP.toString());
                } else {
                    Edition.setText("Aucun joueur trouvé avec le pseudo \"" + pseudo + "\"");
                }
            }
        });  
    }
    private void initListeNiveaux() {
    // Vider la liste déroulante au cas où elle contiendrait déjà des éléments
    ListeNiveaux.removeAllItems();
    
    // Ajouter les différents niveaux à la JComboBox
    ListeNiveaux.addItem("Débutant");
    ListeNiveaux.addItem("Intermédiaire");
    ListeNiveaux.addItem("Avancé");
    ListeNiveaux.addItem("Expert");
    
    // Sélectionner le premier élément par défaut
    ListeNiveaux.setSelectedIndex(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jEast = new javax.swing.JPanel();
        PActions = new javax.swing.JPanel();
        BAfficher = new javax.swing.JButton();
        LPseudo = new javax.swing.JLabel();
        RechPseudo = new javax.swing.JTextField();
        BRecherche = new javax.swing.JButton();
        ListeNiveaux = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        BPhoto = new javax.swing.JButton();
        jCenter = new javax.swing.JPanel();
        jCenterScroll = new javax.swing.JScrollPane();
        Edition = new javax.swing.JTextArea();
        jNorth = new javax.swing.JPanel();
        LTitre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jEast.setLayout(new java.awt.GridLayout(2, 1));

        PActions.setLayout(new java.awt.GridLayout(5, 1));

        BAfficher.setText("Afficher");
        BAfficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAfficherActionPerformed(evt);
            }
        });
        PActions.add(BAfficher);

        LPseudo.setText("Pseudo ?");
        PActions.add(LPseudo);
        PActions.add(RechPseudo);

        BRecherche.setText("Rechercher");
        PActions.add(BRecherche);

        ListeNiveaux.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ListeNiveaux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListeNiveauxActionPerformed(evt);
            }
        });
        PActions.add(ListeNiveaux);

        jEast.add(PActions);

        jPanel5.setLayout(new java.awt.BorderLayout());
        jPanel5.add(BPhoto, java.awt.BorderLayout.CENTER);

        jEast.add(jPanel5);

        getContentPane().add(jEast, java.awt.BorderLayout.EAST);

        jCenter.setLayout(new java.awt.BorderLayout());

        Edition.setColumns(20);
        Edition.setRows(5);
        jCenterScroll.setViewportView(Edition);

        jCenter.add(jCenterScroll, java.awt.BorderLayout.CENTER);

        getContentPane().add(jCenter, java.awt.BorderLayout.CENTER);

        LTitre.setText("Visualisation des Joueurs");
        jNorth.add(LTitre);

        getContentPane().add(jNorth, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BAfficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAfficherActionPerformed
    // Créer un modèle de liste par défaut pour stocker les chaînes de caractères
    DefaultListModel<String> model = new DefaultListModel<>();
    
    // Parcourir tous les joueurs et les ajouter au modèle
    for (Joueur j : lj.getListeJoueurs()) {
        model.addElement(j.toString()); // toString() retourne pseudo ou détails du joueur
    }
    
    // Appliquer le modèle à la zone d'édition (JList)
    Edition.setModel(model);
    }//GEN-LAST:event_BAfficherActionPerformed

    private void ListeNiveauxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListeNiveauxActionPerformed
 // Récupérer le niveau sélectionné dans la liste déroulante
    String niveauSelectionne = (String) ListeNiveaux.getSelectedItem();
    
    // Créer un modèle de liste pour stocker les joueurs filtrés
    DefaultListModel<String> model = new DefaultListModel<>();
    
    // Convertir la chaîne de caractères en entier correspondant au niveau
    int niveau = 0; // Par défaut, débutant
    
    switch(niveauSelectionne) {
        case "Débutant":
            niveau = 1;
            break;
        case "Intermédiaire":
            niveau = 2;
            break;
        case "Avancé":
            niveau = 3;
            break;
        case "Expert":
            niveau = 4;
            break;
    }
    
    // Récupérer tous les joueurs du niveau sélectionné
    for (Joueur j : lj.getJoueurs(niveau)) {
        model.addElement(j.toString());
    }
    
    // Appliquer le modèle à la zone d'édition
    Edition.setModel(model);
    }//GEN-LAST:event_ListeNiveauxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisuJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisuJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisuJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisuJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VisuJoueurDlg dialog = new VisuJoueurDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAfficher;
    private javax.swing.JButton BPhoto;
    private javax.swing.JButton BRecherche;
    private javax.swing.JTextArea Edition;
    private javax.swing.JLabel LPseudo;
    private javax.swing.JLabel LTitre;
    private javax.swing.JComboBox<String> ListeNiveaux;
    private javax.swing.JPanel PActions;
    private javax.swing.JTextField RechPseudo;
    private javax.swing.JPanel jCenter;
    private javax.swing.JScrollPane jCenterScroll;
    private javax.swing.JPanel jEast;
    private javax.swing.JPanel jNorth;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
